# Generated by Django 4.1.6 on 2023-02-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meroshare',
            old_name='seller',
            new_name='linked_to',
        ),
    ]
